<?php

$plugin = array(
  'title' => t('Site wide'),
  'category' => t('Site template'),
  'icon' => 'onerowtwocols.png',
  'theme' => 'site_wide',
  'css' => 'site_wide.css',
  'regions' => array(
    'header_top' => t('Header Top'),
    'header' => t('Header'),
    'navigation' => t('Navigation'),
    'navigation_bottom' => t('Navigation bottom'),
    'page_title' => t('Page title'),
    'feature' => t('Feature'),
    'breadcrumb' => t('Breadcrumb'),
    'content_top' => t('Content top'),
    'content' => t('Content'),
    'content_bottom' => t('Content bottom'),
    'footer_panel_1' => t('Footer Panel 1'),
    'footer_panel_2' => t('Footer Panel 2'),
    'footer_panel_3' => t('Footer Panel 3'),
    'footer_panel_4' => t('Footer Panel 4'),
    'footer_top' => t('Footer Top'),
    'footer' => t('Footer'),
  ),
);
