<?php

/**
 * @file
 * revolution_slider i18n integration module via entity API i18n support.
 *
 * @see EntityDefaultI18nController
 */

/**
 * Implements hook_entity_info_alter().
 */
function revolution_slider_i18n_entity_info_alter(&$info) {
  // Enable i18n support via the entity API.
  $info['revolution_slider_type']['i18n controller class'] = 'EntityDefaultI18nStringController';
}

/**
 * Implements hook_entity_property_info_alter().
 */
function revolution_slider_i18n_entity_property_info_alter(&$info) {
  // Mark some properties as translatable, but also denote that translation
  // works with i18n_string.
  foreach (array('label') as $name) {
    $info['revolution_slider_type']['properties'][$name]['translatable'] = TRUE;
    $info['revolution_slider_type']['properties'][$name]['i18n string'] = TRUE;
  }
}

/**
 * Implements hook_revolution_slider_type_insert().
 */
function revolution_slider_i18n_revolution_slider_type_insert($revolution_slider_type) {
  i18n_string_object_update('revolution_slider_type', $revolution_slider_type);
}

/**
 * Implements hook_revolution_slider_type_update().
 */
function revolution_slider_i18n_revolution_slider_type_update($revolution_slider_type) {
  // Account for name changes.
  if ($revolution_slider_type->original->type != $revolution_slider_type->type) {
    i18n_string_update_context("revolution_slider:revolution_slider_type:{$revolution_slider_type->original->type}:*", "revolution_slider:revolution_slider_type:{$revolution_slider_type->type}:*");
  }
  i18n_string_object_update('revolution_slider_type', $revolution_slider_type);
}

/**
 * Implements hook_revolution_slider_type_delete().
 */
function revolution_slider_i18n_revolution_slider_type_delete($revolution_slider_type) {
  i18n_string_object_remove('revolution_slider_type', $revolution_slider_type);
}
